#!/bin/bash -e

echo "current governor for cpu0 is:"
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

choice=$1
if [[ -z $1 ]];
then
    echo "#############"
    echo "choose one from: "
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
    echo "enter your choice (copy&paste): "
    read choice
fi

echo "urray... changing governor to $choice..."
for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor;
 do echo $choice >"$cpu";
done

echo -e "\n\n current governor for cpu0 is:"

cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
