#!/bin/bash -e

echo "Which display do you want to change brightness?"
xrandr | grep " connected" | cut -f1 -d " "
read  -n 15 -p "display name?" input
read  -n 3 -p "brightness level (0.0 to 1.0)?"  level
xrandr --output $input --brightness $level

